Repository redhat-cop/container-pipelines, pull requests merged in 2020-05, with the labels that each got.

#131 Added link for tekton operator
  basic-spring-boot-tekton/README.md
Labels: approved, lgtm

#132 Add OWNERS file for prow integration
  OWNERS
Labels: approved, lgtm, size/S

#134 Add build namespace to jenkins deployment
  basic-spring-boot/.applier/group_vars/seed-hosts.yml
Labels: approved, lgtm, size/XS
