Repository redhat-cop/container-pipelines, pull requests merged in 2020-06, with the labels that each got.

#139 Fix manual instructions in the Readme file
  basic-spring-boot-tekton/README.md
Labels: approved, lgtm, size/M

#140 Add changes for Task and Pipeline using v1beta1 version instead of v1alpha1
  basic-spring-boot-tekton/.openshift/templates/build.yml
  basic-spring-boot-tekton/README.md
Labels: approved, lgtm, size/M

#141 Add better deployment verification instead of the current sleep step
  basic-spring-boot-tekton/.openshift/templates/build.yml
Labels: approved, lgtm, size/S

#127 Added github workflow action for conftest
  .github/workflows/conftest.yaml
  _test/tests.bats
  cucumber-selenium-grid/applier/templates/jenkins-ephemeral.yml
Labels: approved, enhancement, lgtm, size/M

#142 Added help method to print out failed tests
  .github/workflows/conftest.yaml
  _test/_helpers.bash
  _test/conftest.sh
  _test/tests.bats
Labels: approved, lgtm, size/L

#144 Basic-NGINX: Added Boolean Conversion to String in Jenkinsfile
  basic-nginx/Jenkinsfile
Labels: approved, lgtm, size/XS

#145 Adopt standardized app labels for the basic-nginx app
  basic-nginx/.openshift/builds/template.yml
  basic-nginx/.openshift/deployment/template.yml
Labels: approved, lgtm

#146 Added ci badge to readme
  README.md
Labels: approved, lgtm, size/XS
